### ISSUE TITLE
[Consistency review ] Trademark policy White Paper 

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/trademark_wg#6]
**Consistency Review** - In this phase, the Trademark_policy_White_Paper developed by the WG will be formally reviewed by the GSF members.  After this period, the Working Group will address any submitted issues received prior to formally Approving the White Paper.

1. **Doc for review** - [Trademark_policy_White_Paper](https://github.com/Green-Software-Foundation/trademark_policy/tree/dev/Trademark_policy)

2. Comments to be submitted in this issue or a PR to be submitted against the dev branch.

**NOTE: All comments must be submitted by 28th Sept @ 1200 BST**

**Comment by seanmcilroy29** [comment]
Issue moved to [trademark policy repo](https://github.com/Green-Software-Foundation/trademark_policy/issues/22)

**Comment by atg-abhishek** [comment]
Should we close this issue @seanmcilroy29 ?

**Comment by seanmcilroy29** [comment]
Consistency review closed and Issues resolved
